# Generated by Django 3.1.4 on 2020-12-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_article_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='price',
        ),
    ]
